# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0fcc062cb75b6c52f6c532b1cc6f1021e7b7d1f872f4e171fdbb6d7f3523b76126707562ff0db6441213ac31fedea3d3c24c3e9ed22bfcabd9e6993379b9571


test:
  secret_key_base: 82744b4b0cd9ba7336119d23e3f84abf88def42344e7eb486a297c1a9ba81f20907a81df49cbb16d487fd156dafc5c443ff6ed6f99aaf7d83d54985fa708c329

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: fbd273d7988244fc5f0eb62532b43e0f35789d08cdcfa549395b12075b59e64d04628a8af585e1a81bb083c2dcdc374181dced0cace1d417b00d30e456c8000d

